src/job_tracker/objects/JobApplication__c/JobApplication__c.object-meta.xml
<CustomObject>
    <description>Created for CCA Capstone Demo</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/job_tracker/objects/JobApplication__c/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <inlineHelpText>Date Application Submitted</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

src/job_tracker/objects/JobApplication__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

src/job_tracker/objects/JobApplication__c/fields/Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Date__c</fullName>
    <inlineHelpText>Date to follow up o application</inlineHelpText>
    <label>Follow Up Date</label>
    <type>Date</type>
</CustomField>

src/job_tracker/objects/JobApplication__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <inlineHelpText>Expected Salary For Position</inlineHelpText>
    <label>Salary</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/job_tracker/classes/selectors/JobApplicationsSelector.cls
/**
 * Created by brooksjohnson on 3/29/24.
 */

public  inherited sharing class JobApplicationsSelector extends ApplicationSelector {
    public SObjectType getSObjectType() {
        return JobApplication__c.SObjectType;
    }

    public List<SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                JobApplication__c.Name,
                JobApplication__c.Id,
                JobApplication__c.Application_Date__c,
                JobApplication__c.Follow_Up_Date__c,
                JobApplication__c.Description__c,
                JobApplication__c.Company__c,
                JobApplication__c.Primary_Contact__c,
                JobApplication__c.Salary__c
        };
    }

    public List<JobApplication__c> selectByID(Set<Id> jobApplicationIDs ){
        return (List<JobApplication__c>) selectSObjectsById(jobApplicationIDs);
    }


}