src/formula_force/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTEST-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/formula_force/main/default/objects/Contestant__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active drivers can be a contestant in a race</errorMessage>
        <filterItems>
            <field>Driver__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active drivers are permitted</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

src/formula_force/main/default/classes/domains/ContestantsTriggerHandler.cls
/**
 * Created by bjohnson on 3/22/24.
 */

public with sharing class ContestantsTriggerHandler extends ApplicationDomain {

    public ContestantsTriggerHandler(List<Contestant__c> contestants) {
        super(contestants);
    }

    public override void onValidate() {
        new Contestants(Trigger.new).validate();
    }

    public override void onValidate(Map<Id, SObject> existingRecords) {
        new Contestants(getChangedRecords(new Set<String>{'Driver__c'})).validate();

    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new ContestantsTriggerHandler((List<Contestant__c>) sObjectList);
        }
    }

}