src/formula_force/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTEST-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/formula_force/main/default/objects/Contestant__c/fields/ChampionshipPoints__c.field-meta.xml
<CustomField>
    <fullName>ChampionshipPoints__c</fullName>
    <label>Championship Points</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active drivers can be a contestant in a race</errorMessage>
        <filterItems>
            <field>Driver__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active drivers are permitted</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/RacePosition__c.field-meta.xml
<CustomField>
    <fullName>RacePosition__c</fullName>
    <label>Race Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/formula_force/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/formula_force/main/default/objects/Race__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Races</relationshipLabel>
    <relationshipName>Races</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/formula_force/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/formula_force/main/default/classes/controllers/ContestantControllerTest.cls
/**
 * Created by bjohnson on 11/17/23.
 */

@IsTest
public with sharing class ContestantControllerTest {

    @IsTest
    static void testAwardPoints(){
        //given
        Season__c testSeason = new Season__c();
        insert testSeason;
        Driver__c testDriver = new Driver__c(Name ='Test Driver', DriverId__c = '44');
        insert testDriver;
        Race__c testRace = new Race__c(Name = 'test', Season__c = testSeason.Id);
        insert testRace;
        Contestant__c testContestant = new Contestant__c( Driver__c = testDriver.Id, Race__c = testRace.Id, RacePosition__c = 1);
        insert testContestant;
        //when
        ContestantController.awardPoints(testContestant.Id);
        //then
        Contestant__c updatedContestant = [SELECT Id, ChampionshipPoints__c
        FROM Contestant__c
        WHERE Id =: testContestant.Id];

        Assert.isTrue(updatedContestant.ChampionshipPoints__c == 25, 'It should update the points');
    }

    @IsTest
    static void  itShouldHandleException(){
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        ContestantService serviceMock = (ContestantService)mocks.mock(ContestantService.class);
        fflib_ISObjectUnitOfWork uowMock = (fflib_ISObjectUnitOfWork)mocks.mock(fflib_ISObjectUnitOfWork.class);
        mocks.startStubbing();
        ((fflib_ISObjectUnitOfWork)mocks.doThrowWhen(new ContestantService.contestantServiceException(),uowMock)).commitWork();
        mocks.stopStubbing();
        FormulaForceApplication.UnitOfWork.setMock(uowMock);
        try {
           ContestantController.awardPoints(fflib_IDGenerator.generate(Contestant__c.SObjectType));
            Assert.fail();
        } catch (Exception e) {
            Assert.isTrue(e instanceof AuraHandledException);
        }

    }

    @IsTest
    static void retireFromRace(){
        try {
           ContestantService.retireFromRace(null);
            Assert.fail();
        } catch (Exception e) {
            Assert.isTrue('Not Implemented' == e.getMessage());
        }
    }

}