src/formula_force/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTEST-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/formula_force/main/default/objects/Contestant__c/fields/ChampionshipPoints__c.field-meta.xml
<CustomField>
    <fullName>ChampionshipPoints__c</fullName>
    <label>Championship Points</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/RacePosition__c.field-meta.xml
<CustomField>
    <fullName>RacePosition__c</fullName>
    <label>Race Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/formula_force/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/formula_force/main/default/classes/RaceServiceTest.cls
/**
 * Created by bjohnson on 11/18/23.
 */

@IsTest
private class RaceServiceTest {
    @IsTest
    static void itShouldAwardPoints() {
        //given
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork mockUOW = (fflib_ISObjectUnitOfWork)mocks.mock(fflib_ISObjectUnitOfWork.class);
        RacesSelector mockSelector = (RacesSelector) mocks.mock(RacesSelector.class);
        Race__c mockRace = new Race__c(Id = fflib_IDGenerator.generate(Race__c.SObjectType));
        Contestant__c mockContestant = new Contestant__c(Id = fflib_IDGenerator.generate(Contestant__c.SObjectType),
                RacePosition__c = 1);
        List<Race__c> racesWithContestantsMock = (List<Race__c>) fflib_ApexMocksUtils.makeRelationship(
                List<Race__c>.class,
                new List<Race__c>{mockRace},
                Contestant__c.Race__c,
                new List<List<Contestant__c>>{new List<Contestant__c>{mockContestant}}
        );
        mocks.startStubbing();
        mocks.when(mockSelector.sObjectType()).thenReturn(Race__c.SObjectType);
        mocks.when(mockSelector.selectByIdWithContestants(new Set<Id>{mockRace.Id})).thenReturn(racesWithContestantsMock);
        mocks.stopStubbing();
        FormulaForceApplication.Selector.setMock(mockSelector);
        FormulaForceApplication.UnitOfWork.setMock(mockUOW);
        //when
        RaceService.awardChampionshipPoints(new Set<Id>{mockRace.Id});
        //then
        ((fflib_ISObjectUnitOfWork)mocks.verify(mockUOW, 1)).commitWork();
        ((fflib_ISobjectUnitOfWork)mocks.verify(mockUOW, 1)).registerDirty(fflib_Match.sObjectWith(
                new Map<SObjectField, Object>{
                        Contestant__c.Id  => mockContestant.Id,
                        Contestant__c.RacePosition__c => 1,
                       Contestant__c.ChampionshipPoints__c => 25
                }
        ));

    }
}