src/formula_force/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTEST-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/formula_force/main/default/objects/Contestant__c/fields/ChampionshipPoints__c.field-meta.xml
<CustomField>
    <fullName>ChampionshipPoints__c</fullName>
    <label>Championship Points</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active drivers can be a contestant in a race</errorMessage>
        <filterItems>
            <field>Driver__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active drivers are permitted</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/RacePosition__c.field-meta.xml
<CustomField>
    <fullName>RacePosition__c</fullName>
    <label>Race Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/formula_force/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/formula_force/main/default/objects/Race__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Races</relationshipLabel>
    <relationshipName>Races</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/formula_force/main/default/objects/Race__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Red Flagged</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/formula_force/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/formula_force/main/default/classes/domains/ContestantsTest.cls
/**
 * Created by bjohnson on 3/26/24.
 */

@IsTest
private class ContestantsTest {
    @IsTest
    static void itShouldAddError() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        Race__c race1 = new Race__c(Id = fflib_IDGenerator.generate(Race__c.SObjectType), Status__c = 'Active');
        Race__c race2 = new Race__c(Id = fflib_IDGenerator.generate(Race__c.SObjectType), Status__c = 'Scheduled');
        Contestant__c contestantGood = new Contestant__c( Race__c = race2.Id );
        Contestant__c contestantBad = new Contestant__c( Race__c = race1.Id );
        RacesSelector mockSelector = (RacesSelector) mocks.mock(RacesSelector.class);
        mocks.startStubbing();
        mocks.when(mockSelector.selectById(new Set<Id>{race2.Id, race1.Id}))
                .thenReturn(new List<Race__c>{race1, race2});
        mocks.when(mockSelector.sObjectType()).thenReturn(Race__c.SObjectType);
        mocks.stopStubbing();
        FormulaForceApplication.Selector.setMock(mockSelector);
        //when
        Contestants contestants = new Contestants(new List<Contestant__c>{contestantBad, contestantGood});
        contestants.validate();
        Assert.isTrue(contestantBad.hasErrors(), 'Should have error added');
        Assert.isFalse(contestantGood.hasErrors(), 'Should not have error added');
    }

    @IsTest
    static void itShouldAwardPoints(){
        fflib_ApexMocks mocks = new fflib_ApexMocks();

        // Given
        fflib_SObjectUnitOfWork mockUow = (fflib_SObjectUnitOfWork) mocks.mock(fflib_SObjectUnitOfWork.class);
        FormulaForceApplication.UnitOfWork.setMock(mockUow);
        Id testContestantId = fflib_IDGenerator.generate(Contestant__c.SObjectType);
        List<Contestant__c> testContestants =
                new List<Contestant__c> {
                        new Contestant__c (
                                Id = testContestantId,
                                RacePosition__c = 1 )
                };


        // When
         new Contestants(testContestants).awardChampionshipPoints(mockUow);

        // Then
        ((fflib_SObjectUnitOfWork)
                mocks.verify(mockUow, 1)).registerDirty(
                fflib_Match.sObjectWith(
                        new Map<SObjectField, Object>{
                                Contestant__c.Id => testContestantId,
                                Contestant__c.RacePosition__c => 1,
                                Contestant__c.ChampionshipPoints__c => 25}
                        ));
    }


    @IsTest
    static void itShouldAddErrorsOnChangeIntegration(){
        //given
        Season__c season = new Season__c(Name = '2024');
        insert season;
        Race__c race = new Race__c(Name ='Cool Race', Season__c = season.Id);
        insert race;
        Driver__c driver1 = new Driver__c(Name = 'Test Driver 1', DriverId__c = '123');
        Driver__c driver2 = new Driver__c(Name = 'Test Driver 2', DriverId__c = '456');
        insert new List<Driver__c>{driver2, driver1};
        Contestant__c contestant1 = new Contestant__c(Race__c = race.Id, Driver__c = driver1.Id);
        Contestant__c contestant2 = new Contestant__c(Race__c = race.Id, Driver__c = driver2.Id);
        insert  new List<Contestant__c>{contestant1, contestant2};
        race.Status__c = 'Red Flagged';
        update race;
        contestant1.Driver__c = driver2.Id;
        try {
            update new List<Contestant__c>{contestant2, contestant1};
            Assert.fail('should not reach this line');
        }catch (Exception e){
            System.debug('e=' + e.getMessage());
            Assert.isTrue(e.getMessage().contains('Contestant must be added to a scheduled race'));
        }
    }
}