src/formula_force/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTEST-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/formula_force/main/default/objects/Contestant__c/fields/DNF__c.field-meta.xml
<CustomField>
    <fullName>DNF__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Did Not Finish</inlineHelpText>
    <label>DNF</label>
    <type>Checkbox</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active drivers can be a contestant in a race</errorMessage>
        <filterItems>
            <field>Driver__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active drivers are permitted</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/DriverandRace__c.field-meta.xml
<CustomField>
    <fullName>DriverandRace__c</fullName>
    <formula>Driver__r.Name +&apos; &apos; +  Race__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Driver and Race</label>
    <type>Text</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/Qualification_Lap_Time_1__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Lap_Time_1__c</fullName>
    <label>Qualification Lap Time 1</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/Qualification_Lap_Time_2__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Lap_Time_2__c</fullName>
    <label>Qualification Lap Time 2</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/Qualification_Lap_Time_3__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Lap_Time_3__c</fullName>
    <label>Qualification Lap Time 3</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/RacePosition__c.field-meta.xml
<CustomField>
    <fullName>RacePosition__c</fullName>
    <label>Race Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/formula_force/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/formula_force/main/default/classes/selectors/ContestantsSelector.cls
/**
 * Created by bjohnson on 11/18/23.
 */

public inherited sharing class ContestantsSelector extends fflib_SObjectSelector {

    public List<Schema.SObjectField> getSObjectFieldList(){
       return new List<Schema.SObjectField>{
               Contestant__c.Name,
               Contestant__c.Id,
               Contestant__c.DNF__c,
               Contestant__c.Driver__c,
               Contestant__c.Race__c,
               Contestant__c.Qualification_Lap_Time_1__c,
               Contestant__c.Qualification_Lap_Time_2__c,
               Contestant__c.Qualification_Lap_Time_3__c,
               Contestant__c.DriverandRace__c,
               Contestant__c.RacePosition__c
       };
    }


    public SObjectType getSObjectType() {
        return Contestant__c.SObjectType;
    }

    public List<Contestant__c> selectById(Set<Id> ids) {
        return (List<Contestant__c>) super.selectSObjectsById(ids);
    }
}