src/formula_force/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTEST-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/formula_force/main/default/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/formula_force/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/formula_force/main/default/classes/services/RaceServiceImpl.cls
/**
 * Created by bjohnson on 12/1/23.
 */

public with sharing class RaceServiceImpl implements IRaceService {

    public Map<Id, List<RaceServiceResults.ProvisionalResult>> calculateProvisionalResults(Set<Id> raceIds){
        throw new RaceService.RaceServiceException('Not Implemented');
    }

    public void applyRaceResults(Map<Id, List<RaceServiceResults.ProvisionalResult>> provisionalResultsByRaceId) {
        throw new RaceService.RaceServiceException('Not Implemented');
    }

    public void awardChampionshipPoints(Set<Id> raceIds) {
        fflib_ISObjectUnitOfWork uow = FormulaForceApplication.UnitOfWork.newInstance();
       RacesSelector racesSelector = (RacesSelector)FormulaForceApplication.Selector.newInstance(Race__c.SObjectType);
        List<Contestant__c> contestants = new List<Contestant__c>();
        for (Race__c race : racesSelector.selectByIdWithContestants(raceIds)){
            contestants.addAll(race.Contestants__r);
        }
        //delegate to Contestant Service
        ContestantService.awardChampionshipPoints(uow, contestants);
        uow.commitWork();
    }
}