src/formula_force/main/default/objects/Championship_Points__mdt/Championship_Points__mdt.object-meta.xml
<CustomObject>
    <label>Championship Points</label>
    <pluralLabel>Championship Points</pluralLabel>
</CustomObject>

src/formula_force/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTEST-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/formula_force/main/default/objects/Contestant__c/fields/ChampionshipPoints__c.field-meta.xml
<CustomField>
    <fullName>ChampionshipPoints__c</fullName>
    <label>Championship Points</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/RacePosition__c.field-meta.xml
<CustomField>
    <fullName>RacePosition__c</fullName>
    <label>Race Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/formula_force/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/formula_force/main/default/objects/Race__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Red Flagged</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/formula_force/main/default/classes/domains/Contestants.cls
/**
 * Created by bjohnson on 3/25/24.
 */

public with sharing class Contestants extends fflib_SObjects {

    public Contestants(List<Contestant__c> contestants) {
        super(contestants, Contestant__c.SObjectType);
    }

    public void validate() {
        validateRaceIsScheduled();
    }

    public List<Contestant__c> getContestants(){
        return (List<Contestant__c>) getRecords();
    }


    private void validateRaceIsScheduled() {
        Set<Id> raceIds = getIdFieldValues(Contestant__c.Race__c);
        RacesSelector selector = (RacesSelector) FormulaForceApplication.Selector.newInstance(Race__c.SObjectType);
        Map<Id, Race__c> racesById = new Map<Id, Race__c>((List<Race__c>)selector.selectById(raceIds));
        for (Contestant__c contestant : (List<Contestant__c>) getRecords()) {
            Race__c relatedRace = racesById.get(contestant.Race__c);
            if (relatedRace.Status__c != 'Scheduled') {
                contestant.addError('Contestant must be added to a scheduled race');
            }
        }
    }

    public void awardChampionshipPoints(fflib_ISObjectUnitOfWork uow){
        Map<Integer, Championship_Points__mdt> pointsByTrackPosition =
                new ChampionshipPointsSelector().pointsByTrackPosition();
        for(Contestant__c contestant : getContestants()){
            Championship_Points__mdt points = pointsByTrackPosition.get(Integer.valueOf(contestant.RacePosition__c));
            if (points != null ) {
               contestant.ChampionshipPoints__c = points.PointsAwarded__c;
                uow.registerDirty(contestant);
            }
        }
    }

    public class Constructor implements fflib_IDomainConstructor{
        public fflib_SObjects construct(List<Object> objects){
            return new Contestants((List<SObject>) objects);
        }
    }
}