src/formula_force/main/default/objects/Championship_Points__mdt/Championship_Points__mdt.object-meta.xml
<CustomObject>
    <label>Championship Points</label>
    <pluralLabel>Championship Points</pluralLabel>
</CustomObject>

src/formula_force/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTEST-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/formula_force/main/default/objects/Contestant__c/fields/ChampionshipPoints__c.field-meta.xml
<CustomField>
    <fullName>ChampionshipPoints__c</fullName>
    <label>Championship Points</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/RacePosition__c.field-meta.xml
<CustomField>
    <fullName>RacePosition__c</fullName>
    <label>Race Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/formula_force/main/default/classes/services/ContestantService.cls
/**
 * Created by bjohnson on 11/18/23.
 */

public with sharing class ContestantService {

    public class contestantServiceException extends Exception{}
    public static void awardChampionshipPoints(Set<Id> contestantIds){
        fflib_ISObjectUnitOfWork uow = FormulaForceApplication.UnitOfWork.newInstance();
        awardChampionshipPoints(uow, FormulaForceApplication.Selector.selectById(contestantIds));
        uow.commitWork();
    }
    public static void awardChampionshipPoints(fflib_ISObjectUnitOfWork uow, List<Contestant__c> contestants){
        ChampionshipPointsSelector championshipPointsSelector =  (ChampionshipPointsSelector) FormulaForceApplication.Selector.newInstance(
                Championship_Points__mdt.SObjectType
        );
        Map<Integer, Championship_Points__mdt> pointsByTrackPosition = championshipPointsSelector.pointsByTrackPosition();
        for(Contestant__c contestant : contestants){
            Championship_Points__mdt points = pointsByTrackPosition.get(Integer.valueOf(contestant.RacePosition__c));
            if (points != null) {
                contestant.ChampionshipPoints__c = points.PointsAwarded__c;
            }
            uow.registerDirty(contestant);
        }
    }
    public static void retireFromRace(List<RaceRetirement> raceRetirements){
       throw new contestantServiceException('Not implemented');
    }
    public class RaceRetirement {
        public Id contestantId;
        public String reason;
    }
}