src/formula_force/main/default/objects/Championship_Points__mdt/Championship_Points__mdt.object-meta.xml
<CustomObject>
    <label>Championship Points</label>
    <pluralLabel>Championship Points</pluralLabel>
</CustomObject>

src/formula_force/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTEST-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/formula_force/main/default/objects/Contestant__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only active drivers can be a contestant in a race</errorMessage>
        <filterItems>
            <field>Driver__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active drivers are permitted</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

src/formula_force/main/default/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/formula_force/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/formula_force/main/default/objects/Race__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Races</relationshipLabel>
    <relationshipName>Races</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/formula_force/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/formula_force/main/default/objects/Service__mdt/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <label>Apex Class</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

src/formula_force/main/default/classes/FormulaForceApplication.cls
/**
 * Created by bjohnson on 11/18/23.
 */

public with sharing class FormulaForceApplication {

    public static final fflib_Application.UnitOfWorkFactory UnitOfWork =
            new UnitOfWorkFactory(
                   new List<SObjectType>{
                           Driver__c.SObjectType,
                           Season__c.SObjectType,
                           Race__c.SObjectType,
                           Contestant__c.SObjectType});

    public static final fflib_Application.SelectorFactory Selector =
            new fflib_Application.SelectorFactory(
                    new Map<SObjectType, Type>{
                            Contestant__c.SObjectType => ContestantsSelector.class,
                            Race__c.SObjectType => RacesSelector.class,
                            Championship_Points__mdt.SObjectType => ChampionshipPointsSelector.class
                    }
            );

    public static final fflib_Application.ServiceFactory Service =
            new FormulaForceApplication.ServiceFactory(
                    new Map<Type, Type>{
                            IRaceService.class => RaceServiceImpl.class
                    }
            );

    public static final fflib_Application.DomainFactory Domain = new fflib_Application.DomainFactory(
            FormulaForceApplication.Selector,
            new Map<SObjectType, Type>{
                    Driver__c.SObjectType => Drivers.Constructor.class
            }
    );

    private class ServiceFactory extends fflib_Application.ServiceFactory{
        private Map<String, String> servicesByClassName = new Map<String, String>();

        public ServiceFactory(Map<Type, Type> serviceInterfaceByServiceImplType ){
            super(serviceInterfaceByServiceImplType);
            //map of overriden services
            for (Service__mdt serviceOverride : Service__mdt.getAll().values()){
                servicesByClassName.put(serviceOverride.DeveloperName, serviceOverride.Apex_Class__c);
            }
        }

        public override Object newInstance(Type serviceInterfaceType ){
            if(!Test.isRunningTest() && servicesByClassName.containsKey(serviceInterfaceType.getName())){
                String overridenServiceImpl = servicesByClassName.get(serviceInterfaceType.getName());
                return Type.forName(overridenServiceImpl).newInstance();
            }
            return super.newInstance(serviceInterfaceType);
        }
    }

    public static void throwAuraHandledException(Exception e) {
        String message = e.getMessage();
        AuraHandledException error = new AuraHandledException(message);
        error.setMessage(message); // Apex tests can assert message
        throw error;
    }

}