src/car_hunter/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/car_hunter/main/default/objects/Car__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <label>Manufacturer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Renault</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/formula_force/main/default/objects/Car__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core/main/default/classes/selectors/CarsSelector.cls
/**
 * Created by bjohnson on 3/26/24.
 */

public inherited sharing class CarsSelector extends ApplicationSelector {

    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField>{
                Car__c.Name,
                Car__c.Id,
                Car__c.Manufacturer__c,
                Car__c.MSRP__c,
                Car__c.Description__c,
                Car__c.Weight__c
        };
    }
    public SObjectType getSObjectType(){
        return Car__c.SObjectType;
    }

    public List<Car__c> selectById(Set<Id> carIds){
        return selectSObjectsById(carIds);
    }

}